FROM node:22.6.0

ARG SPOTIFY_BASE_API_URL
ARG SPOTIFY_CLIENT_ID
ARG SPOTIFY_CLIENT_SECRET
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL
ARG NEXT_PUBLIC_URL

ENV SPOTIFY_BASE_API_URL=$SPOTIFY_BASE_API_URL
ENV SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID
ENV SPOTIFY_CLIENT_SECRET=$SPOTIFY_CLIENT_SECRET
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV NEXT_PUBLIC_URL=$NEXT_PUBLIC_URL

WORKDIR /app

COPY . .

RUN apt-get update && apt-get install -y \
    bash \
    curl \
    git \
    unzip

RUN curl -fsSL https://bun.sh/install | bash

ENV PATH="/root/.bun/bin:${PATH}"

RUN bun install

RUN bun run build

CMD ["bun", "start"]